# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: Eclipse SDV

url: https://eclipse-sdv-landscape.github.io

base_path: /sdv-landscape/pr-preview/pr-30

colors:
  # Grid/Card/Menu color
  color1: "rgba(240, 108, 1, 1)"

  #Filter buttons color
  color2: "rgba(240, 108, 1, 1)"

  color3: "rgba(65, 88, 208, 1)"
  color4: "rgba(155, 65, 106, 0.8)"

  #subcategory color
  color5: "rgba(89, 44, 81, 1)"
  #subcategory color
  color6: "rgba(176, 102, 148, 1)"

  color7: "rgba(247, 246, 248, 1)"

description: Eclipse SDV

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Graduated

footer:
  links:
    facebook: "https://www.facebook.com/--"
    flickr: "https://www.flickr.com/people/108559379@N08/"
    github: "https://github.com/eclipse-sdv-landscape/sdv-landscape"
    homepage: "https://eclipsesdv.org/"
    instagram: "https://www.instagram.com/eclipsesdv/"
    linkedin: "https://www.linkedin.com/company/software-defined-vehicle/"
    slack: "https://join.slack.com/t/sdvworkinggroup/shared_invite/zt-3c5ied1nk-Mk87s4kOX7ipcNo_VktlWg"
    twitter: "https://x.com/SDVeclipse/"
    youtube: "https://www.youtube.com/@EclipseFdn"
  logo: "./assets/sdv-logo-color-white.svg"

grid_items_size: large

groups:
  - name: SDV Projects
    categories:
      - Tooling Devops
      - Distributions and Frameworks
      - RTOS
      - Example Applications
      - Service Fabric and Communication
      - Runtime and Orchestration
      - AI
      - Unmapped

header:
  links:
    github: "https://github.com/eclipse-sdv-landscape/sdv-landscape"
  logo: "./assets/sdv-logo-color.svg"

screenshot_width: 1500
