name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: read

jobs:
  maturity-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect SDV maturity artifacts
        uses: eclipse-dash/quevee@v1
        id: quevee_manifest
        with:
          release_url: ${{ github.event.release.html_url }}
          artifacts_documentation: README.md
          artifacts_readme: README.md
          artifacts_testing: .github/workflows/build.yml
          artifacts_release_process: .github/workflows/deploy.yml

      - name: Upload SDV maturity manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee_manifest.outputs.manifest_file }}
          tag: ${{ github.event.release.tag_name }}
